### ISSUE TITLE
[FEATURE]  초기 Table 설계 & erd cloud

### ISSUE THREAD

**Issue by Soo186** [rolling-paper-toy/back-end#2]
## #️⃣ 요청 유형

> 해당되는 항목을 선택해주세요.
- [x] 새로운 기능 추가
- [ ] 기존 기능 개선
- [ ] 성능 개선

## #️⃣ 어떤 기능인가요?

[FEATURE] 초기 Table 설계 & ERD 작성

## #️⃣ 이 기능이 필요한 이유는 무엇인가요?

프로젝트의 데이터 구조를 명확히 하고 개발 팀원 간의 이해를 통일하기 위해 초기 테이블 설계와 ERD 작성이 필요합니다.

## #️⃣ 작업 상세 내용

- [x] 주요 엔티티 식별 및 정의
- [x] 테이블 간 관계 설정
- [x]  ERD 작성 및 검토

## 📎 참고할만한 자료 (선택)
ERD 도구 활용

**Comment by pangwoo96** [comment]
테이블 설계하고 ERD까지 완성했습니다. 추가적인 이슈로 Entity 만들어서 공유하겠습니다!!

**Comment by Soo186** [comment]
<img width="1008" alt="스크린샷 2024-10-01 오후 1 47 56" src="https://github.com/user-attachments/assets/866de653-8ef9-47d6-a560-73f60f07f27b">


초기 테이블 설계 완료 사진입니다.  @pangwoo96  @dilkusha27
