### ISSUE TITLE
[MAINTENANCE] 보안 파일 관리 개선

### ISSUE THREAD

**Issue by Soo186** [rolling-paper-toy/back-end#63]
## #️⃣ 작업 내용

 설정 파일을 기존 .properties 형식에서 .yml 형식으로 변환
 .env 파일을 .env.example 파일로 변환하여 Git에 공유 (개발 시 필요한 형식은 제공하되, 실제 값은 제외)
 메신저를 통한 실제 민감 정보 공유 (예: 데이터베이스 비밀번호, Oauth 환경설정 등)

## #️⃣ 작업이 필요한 이유

현재 프로젝트의 보안 관리가 강화될 필요가 있습니다. Docker 환경에서 팀원들이 프로젝트를 클론할 때 안전한 환경을 제공하기 위해 설정 파일을 재구성하고 민감 정보가 포함된 파일을 직접 관리할 수 있도록 정리하고자 합니다. 
이번 **유지보수 작업은 민감 데이터의 노출 위험을 줄이고 배포 전 보안 관리 수준을 강화하는 것**이 목적입니다.

## #️⃣ 작업 상세 내용

- [ ] TODO
- [ ] TODO
- [ ] TODO

## 📎 참고 자료 (선택)

> 관련 문서, 스크린샷, 또는 예시 등이 있다면 여기에 첨부해주세요

**Comment by pangwoo96** [comment]
작업 과정에서 현재 properties 파일들이 github에 올라가있는데 이 부분도 제거해주시면 좋을 것 같습니다!!
